### ISSUE TITLE
python finetune_lora.py 时报错。麻烦看下问题。

### ISSUE THREAD

**Issue by tiaotiaosong** [mark1879/Baichuan-13B-Finetuning#3]
![image](https://github.com/mark1879/Baichuan-13B-Finetuning/assets/29913710/0a1c5037-cfda-48a9-b0b9-a5bf1e53178e)

**Comment by mark1879** [comment]
没遇到过这样的问题。基座模型是最新的吧？参数都传了吧？

**Comment by smartswordsman** [comment]
你好，请问一下解决了吗？我也遇到这个问题了。

**Comment by chenyingzhou** [comment]
你好，我也遇到了这个问题，原因是baichuan模型没有实现get_input_embeddings，但我不知道怎么解决

**Comment by chenyingzhou** [comment]
> 没遇到过这样的问题。基座模型是最新的吧？参数都传了吧？

解决了，不要用modelscope，用hf

**Comment by chenyingzhou** [comment]
> ![image](https://user-images.githubusercontent.com/29913710/252877801-0a1c5037-cfda-48a9-b0b9-a5bf1e53178e.png)

用huggingface，不要用modelscope，两边配置不一样

**Comment by tiaotiaosong** [comment]
重新从hugface上下载一下模型就可以了。
